services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookshare-app
    env_file:
      - .env
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-bookshare}
      DB_USERNAME: ${DB_USERNAME:-bookshare}
      DB_PASSWORD: ${DB_PASSWORD:-bookshare}
    volumes:
      - ./:/var/www/html
      - app_vendor:/var/www/html/vendor
      - app_node:/var/www/html/node_modules
    ports:
      - "9000:9000"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z 127.0.0.1 9000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 12
    networks:
      - bookshare
    depends_on:
      mysql:
        condition: service_healthy
      node:
        condition: service_started

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_bookshare
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - bookshare

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_bookshare
    ports:
      - "3000:3000"
    networks:
      - bookshare

  nginx:
    image: nginx:alpine
    container_name: bookshare-nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - bookshare

  node:
    image: node:20-alpine
    container_name: bookshare-node
    working_dir: /var/www/html
    command: sh -c "npm ci && VITE_DEV_SERVER_URL=http://localhost:5173 npm run dev -- --host=0.0.0.0 --port=5173 --strictPort"
    volumes:
      - ./:/var/www/html
      - app_node:/var/www/html/node_modules
    ports:
      - "5173:5173" # Vite dev server
    environment:
      - VITE_HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true
      - VITE_DEV_SERVER_URL=http://localhost:5173
    networks:
      - bookshare

  mysql:
    image: mysql:8.0
    container_name: bookshare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-bookshare}
      MYSQL_USER: ${DB_USERNAME:-bookshare}
      MYSQL_PASSWORD: ${DB_PASSWORD:-bookshare}
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - bookshare

volumes:
  db_data:
  app_vendor:
  app_node:


networks:
  bookshare:
    driver: bridge
